"""add questions table   schema changed

Revision ID: 395b1d8a1417
Revises: d4ef5c9ea055
Create Date: 2025-08-24 18:37:23.810553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '395b1d8a1417'
down_revision: Union[str, Sequence[str], None] = 'd4ef5c9ea055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('ques', sa.Text(), nullable=False))
    op.add_column('questions', sa.Column('options', sa.JSON(), nullable=False))
    op.add_column('questions', sa.Column('answer', sa.Integer(), nullable=True))
    op.drop_column('questions', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('text', mysql.TEXT(), nullable=False))
    op.drop_column('questions', 'answer')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'ques')
    # ### end Alembic commands ###
