"""Make datetime fields timezone aware

Revision ID: 4cf9f9ffe458
Revises: 4dfc4f0c1ffa
Create Date: 2025-08-25 11:00:39.706152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf9f9ffe458'
down_revision: Union[str, Sequence[str], None] = '4dfc4f0c1ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
