"""add user role superadmin

Revision ID: 4dfc4f0c1ffa
Revises: 395b1d8a1417
Create Date: 2025-08-24 20:30:36.312781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfc4f0c1ffa'
down_revision: Union[str, Sequence[str], None] = '395b1d8a1417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
