"""Simplify TestSession model (remove proctoring/webcam fields)

Revision ID: c8c112126dcf
Revises: 4cf9f9ffe458
Create Date: 2025-08-29 19:02:41.492908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8c112126dcf'
down_revision: Union[str, Sequence[str], None] = '4cf9f9ffe458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # --- Drop foreign key first (constraint name may vary, adjust if needed) ---
    op.drop_constraint('proctor_events_ibfk_1', 'proctor_events', type_='foreignkey')

    # --- Then drop index ---
    op.drop_index(op.f('ix_proctor_events_session_id'), table_name='proctor_events')

    # --- Finally drop table ---
    op.drop_table('proctor_events')

    # --- Drop unnecessary columns from test_sessions ---
    op.drop_column('test_sessions', 'webcam_required')
    op.drop_column('test_sessions', 'invalidated')
    op.drop_column('test_sessions', 'suspicious_flags')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('suspicious_flags', mysql.JSON(), nullable=False))
    op.add_column('test_sessions', sa.Column('invalidated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('test_sessions', sa.Column('webcam_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_table('proctor_events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('payload', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], name=op.f('proctor_events_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_proctor_events_session_id'), 'proctor_events', ['session_id'], unique=False)
    # ### end Alembic commands ###
