"""add questions table and test relation deletes

Revision ID: ef2033354e38
Revises: a6754e3aedca
Create Date: 2025-08-24 16:54:13.984675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2033354e38'
down_revision: Union[str, Sequence[str], None] = 'a6754e3aedca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('note_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tests_note_id'), 'tests', ['note_id'], unique=False)
    op.create_foreign_key(None, 'tests', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_index(op.f('ix_tests_note_id'), table_name='tests')
    op.drop_column('tests', 'note_id')
    # ### end Alembic commands ###
